version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - v7-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v7-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  docs:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: docs
  python38-drf310:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: 'py38-django{22,30}-drf310-tests'
  python39-drf310:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: 'py39-django{22,30}-drf310-tests'
  python38-other:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: 'py38-django{22,30,31}-drf{311,312}-tests'
  python39-other:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: 'py39-django{22,30,31}-drf{311,312}-tests'
  djangomaster:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - restore_cache:
          keys:
            - v7-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
      - run:
          name: install dependencies
          command: pip install --user tox
      - run:
          name: run tox
          # Allow failures for django master tests
          command: ~/.local/bin/tox -r || true
      - save_cache:
          paths:
            - .hypothesis
            - .tox
            - ~/.cache/pip
            - ~/.local
            - ./eggs
          key: v7-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: 'py39-djangomaster-drf312-tests'
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: lint

workflows:
  version: 2
  test:
    jobs:
      - docs
      - python38-drf310
      - python39-drf310
      - python38-other
      - python39-other
      - djangomaster
      - lint
